import json
import shutil
from pathlib import Path


CELL_SOURCE = [
    "# Speed benchmark (variable number of models) over a full 24h day (288 steps)\n",
    "# - Runs OpenDSS once to compute the daily voltages\n",
    "# - Runs each GNN checkpoint to compute daily voltages\n",
    "# - Reports device (CPU/GPU), total time, and mean time/step\n\n",
    "import os\n",
    "import time\n",
    "import numpy as np\n",
    "import torch\n\n",
    "import run_injection_dataset as inj\n",
    "import run_loadtype_dataset as lt\n\n",
    "from torch_geometric.data import Data\n\n",
    "from run_gnn3_overlay_7 import load_model_for_inference\n",
    "from compare_two_models_daily import build_x_for_model, _resolve_node_list, _get_full_master_node_list\n\n",
    "# ---- Configure checkpoints here (variable length) ----\n",
    "CKPT_PATHS = [\n",
    "    # r\"models_gnn2/loadtype/light_emb_h96_depth2_best.pt\",\n",
    "    # r\"models_gnn2/loadtype/light_emb_h96_depth2_phase_onehot_best.pt\",\n",
    "]\n\n",
    "if len(CKPT_PATHS) == 0:\n",
    "    raise ValueError(\"Set CKPT_PATHS to one or more .pt checkpoint paths.\")\n\n",
    "device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
    "print(\"Device:\", device, \"| torch.cuda.is_available()=\", torch.cuda.is_available())\n\n",
    "# Resolve node list (89 nodes, training order) using the first checkpoint\n",
    "node_names_master = _resolve_node_list(CKPT_PATHS[0])\n",
    "N = len(node_names_master)\n",
    "print(\"Nodes: N=\", N)\n\n",
    "# Electrical distance needs the full 95-node master list (matches dataset generation)\n",
    "ckpt0 = torch.load(CKPT_PATHS[0], map_location=\"cpu\", weights_only=False)\n",
    "dataset_dir0 = ckpt0.get(\"config\", {}).get(\"dataset\", None) or \"datasets_gnn2/loadtype\"\n",
    "edge_csv = os.path.join(\"datasets_gnn2\", \"loadtype\", \"gnn_edges_phase_static.csv\")\n",
    "if not os.path.exists(edge_csv) and dataset_dir0:\n",
    "    cand = os.path.join(dataset_dir0, \"gnn_edges_phase_static.csv\")\n",
    "    if os.path.exists(cand):\n",
    "        edge_csv = cand\n",
    "full_node_list = _get_full_master_node_list(os.path.dirname(edge_csv))\n",
    "node_to_electrical_dist = lt._compute_electrical_distance_from_source(full_node_list, edge_csv)\n\n",
    "# OpenDSS setup\n",
    "P_BASE = float(inj.BASELINE[\"P_load_total_kw\"])\n",
    "Q_BASE = float(inj.BASELINE[\"Q_load_total_kvar\"])\n",
    "PV_BASE = float(inj.BASELINE[\"P_pv_total_kw\"])\n\n",
    "inj.compile_once()\n",
    "inj.setup_daily()\n\n",
    "# Load daily profiles (same as dataset generation)\n",
    "dss_path = inj.compile_once()\n",
    "inj.setup_daily()\n",
    "csvL_token, _ = inj.find_loadshape_csv_in_dss(dss_path, \"5minDayShape\")\n",
    "csvPV_token, _ = inj.find_loadshape_csv_in_dss(dss_path, \"IrradShape\")\n",
    "mL = inj.read_profile_csv_two_col_noheader(inj.resolve_csv_path(csvL_token, dss_path), npts=inj.NPTS, debug=False)\n",
    "mPV = inj.read_profile_csv_two_col_noheader(inj.resolve_csv_path(csvPV_token, dss_path), npts=inj.NPTS, debug=False)\n\n",
    "# Use same bus_to_phases as dataset generation\n",
    "_, _, _, bus_to_phases = inj.get_all_bus_phase_nodes()\n",
    "loads_dss, dev_to_dss_load, dev_to_busph_load = inj.build_load_device_maps(bus_to_phases)\n",
    "pv_dss, pv_to_dss, pv_to_busph = inj.build_pv_device_maps()\n",
    "rng = np.random.default_rng(0)\n\n",
    "# ---- Task A: OpenDSS daily voltages + time ----\n",
    "t0 = time.perf_counter()\n",
    "open_dss_solve_s = 0.0\n",
    "for t in range(inj.NPTS):\n",
    "    inj.set_time_index(t)\n",
    "    _r, busphP_load, busphQ_load, busphP_pv, busphQ_pv, busph_per_type = lt._apply_snapshot_with_per_type(\n",
    "        P_load_total_kw=P_BASE, Q_load_total_kvar=Q_BASE, P_pv_total_kw=PV_BASE,\n",
    "        mL_t=float(mL[t]), mPV_t=float(mPV[t]),\n",
    "        loads_dss=loads_dss, dev_to_dss_load=dev_to_dss_load, dev_to_busph_load=dev_to_busph_load,\n",
    "        pv_dss=pv_dss, pv_to_dss=pv_to_dss, pv_to_busph=pv_to_busph,\n",
    "        sigma_load=0.0, sigma_pv=0.0, rng=rng,\n",
    "    )\n",
    "    t_s = time.perf_counter()\n",
    "    inj.dss.Solution.Solve()\n",
    "    open_dss_solve_s += time.perf_counter() - t_s\n",
    "open_dss_total_s = time.perf_counter() - t0\n",
    "print(\"\\nOpenDSS (24h):\")\n",
    "print(\"  total wall time: %.4f s | mean/step: %.3f ms\" % (open_dss_total_s, 1000*open_dss_total_s/inj.NPTS))\n",
    "print(\"  solve-only time: %.4f s | mean/step: %.3f ms\" % (open_dss_solve_s, 1000*open_dss_solve_s/inj.NPTS))\n\n",
    "# Precompute per-timestep OpenDSS-derived quantities needed for features\n",
    "busph_ctx = [None] * inj.NPTS\n\n",
    "inj.compile_once()\n",
    "inj.setup_daily()\n",
    "for t in range(inj.NPTS):\n",
    "    inj.set_time_index(t)\n",
    "    _r, busphP_load, busphQ_load, busphP_pv, busphQ_pv, busph_per_type = lt._apply_snapshot_with_per_type(\n",
    "        P_load_total_kw=P_BASE, Q_load_total_kvar=Q_BASE, P_pv_total_kw=PV_BASE,\n",
    "        mL_t=float(mL[t]), mPV_t=float(mPV[t]),\n",
    "        loads_dss=loads_dss, dev_to_dss_load=dev_to_dss_load, dev_to_busph_load=dev_to_busph_load,\n",
    "        pv_dss=pv_dss, pv_to_dss=pv_to_dss, pv_to_busph=pv_to_busph,\n",
    "        sigma_load=0.0, sigma_pv=0.0, rng=rng,\n",
    "    )\n",
    "    inj.dss.Solution.Solve()\n",
    "    if not inj.dss.Solution.Converged():\n",
    "        continue\n",
    "    busphP_pv_actual, busphQ_pv_actual = inj.get_pv_actual_pq_by_busph(pv_to_dss, pv_to_busph)\n",
    "    pwr = inj.dss.Circuit.TotalPower()\n",
    "    P_grid = -float(pwr[0])\n",
    "    Q_grid = -float(pwr[1])\n",
    "    sum_p_load = float(sum(busphP_load.values()))\n",
    "    sum_q_load = float(sum(busphQ_load.values()))\n",
    "    sum_p_pv_actual = float(sum(busphP_pv_actual.values()))\n",
    "    sum_q_pv_actual = float(sum(busphQ_pv_actual.values()))\n",
    "    sum_q_cap = float(inj.total_cap_q_kvar(node_names_master))\n",
    "    p_sys_balance = sum_p_load - sum_p_pv_actual\n",
    "    q_sys_balance = sum_q_load + sum_q_pv_actual - sum_q_cap\n",
    "    busph_ctx[t] = (busphP_load, busphQ_load, busphP_pv_actual, busph_per_type, busphQ_pv_actual, P_grid, Q_grid, p_sys_balance, q_sys_balance)\n\n",
    "# ---- Task B: Each model daily voltages + time ----\n",
    "results = []\n",
    "for ckpt_path in CKPT_PATHS:\n",
    "    model, static = load_model_for_inference(ckpt_path, device=device)\n",
    "    cfg = static[\"config\"]\n",
    "    node_in_dim = int(cfg.get(\"node_in_dim\", 2))\n",
    "    edge_index = static[\"edge_index\"].to(device)\n",
    "    edge_attr = static[\"edge_attr\"].to(device)\n",
    "    edge_id = static[\"edge_id\"].to(device)\n",
    "    t_model = 0.0\n",
    "    if device.type == \"cuda\":\n",
    "        with torch.no_grad():\n",
    "            x0 = torch.zeros((N, node_in_dim), dtype=torch.float32, device=device)\n",
    "            g0 = Data(x=x0, edge_index=edge_index, edge_attr=edge_attr, edge_id=edge_id, num_nodes=N)\n",
    "            _ = model(g0)\n",
    "            torch.cuda.synchronize()\n",
    "    for t in range(inj.NPTS):\n",
    "        ctx = busph_ctx[t]\n",
    "        if ctx is None:\n",
    "            continue\n",
    "        busphP_load, busphQ_load, busphP_pv_actual, busph_per_type, busphQ_pv_actual, P_grid, Q_grid, p_sys_balance, q_sys_balance = ctx\n",
    "        X = build_x_for_model(\n",
    "            node_in_dim,\n",
    "            node_names_master=node_names_master,\n",
    "            busphP_load=busphP_load,\n",
    "            busphQ_load=busphQ_load,\n",
    "            busphP_pv=busphP_pv_actual,\n",
    "            busph_per_type=busph_per_type,\n",
    "            P_grid=P_grid,\n",
    "            Q_grid=Q_grid,\n",
    "            node_to_electrical_dist=node_to_electrical_dist,\n",
    "            p_sys_balance=p_sys_balance,\n",
    "            q_sys_balance=q_sys_balance,\n",
    "            busphQ_pv=busphQ_pv_actual,\n",
    "        )\n",
    "        x_t = torch.tensor(X, dtype=torch.float32, device=device)\n",
    "        g = Data(x=x_t, edge_index=edge_index, edge_attr=edge_attr, edge_id=edge_id, num_nodes=N)\n",
    "        if device.type == \"cuda\":\n",
    "            torch.cuda.synchronize()\n",
    "        t0m = time.perf_counter()\n",
    "        with torch.no_grad():\n",
    "            _ = model(g)\n",
    "        if device.type == \"cuda\":\n",
    "            torch.cuda.synchronize()\n",
    "        t_model += time.perf_counter() - t0m\n",
    "    results.append((ckpt_path, t_model))\n",
    "    print(\"\\nModel:\", os.path.basename(ckpt_path))\n",
    "    print(\"  total forward time: %.4f s | mean/step: %.3f ms\" % (t_model, 1000*t_model/inj.NPTS))\n\n",
    "print(\"\\nSummary:\")\n",
    "print(\"  Device:\", device)\n",
    "print(\"  OpenDSS wall total: %.4f s | mean/step: %.3f ms\" % (open_dss_total_s, 1000*open_dss_total_s/inj.NPTS))\n",
    "print(\"  OpenDSS solve total: %.4f s | mean/step: %.3f ms\" % (open_dss_solve_s, 1000*open_dss_solve_s/inj.NPTS))\n",
    "for ckpt_path, t_model in results:\n",
    "    print(\"  %s: total=%.4fs | mean/step=%.3fms\" % (os.path.basename(ckpt_path), t_model, 1000*t_model/inj.NPTS))\n",
]


def main() -> None:
    nb_path = Path("GNN2.ipynb")
    if not nb_path.exists():
        raise FileNotFoundError("GNN2.ipynb not found in current directory.")

    backup = nb_path.with_suffix(".ipynb.bak")
    shutil.copyfile(nb_path, backup)

    nb = json.loads(nb_path.read_text(encoding="utf-8"))
    cells = nb.get("cells", [])
    insert_idx = 37  # right after the plotting cell (cell 36)
    insert_idx = min(insert_idx, len(cells))

    new_cell = {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": CELL_SOURCE,
    }

    cells.insert(insert_idx, new_cell)
    nb["cells"] = cells
    nb_path.write_text(json.dumps(nb, ensure_ascii=False, indent=1), encoding="utf-8")
    print(f"Inserted speed benchmark cell at index {insert_idx}. Backup: {backup}")


if __name__ == "__main__":
    main()

